// Package service provides shared scaffolding for hybrid API/RPC services.
package service

// FileOwner identifies which generator owns a given output file.
type FileOwner string

const (
	// OwnerShared means the file is generated by SharedScaffold and should
	// not be overwritten by transport-specific generators.
	OwnerShared FileOwner = "shared"

	// OwnerAPI means the file is generated and owned by the API (Hertz) generator.
	OwnerAPI FileOwner = "api"

	// OwnerRPC means the file is generated and owned by the RPC (Kitex) generator.
	OwnerRPC FileOwner = "rpc"
)

// ownershipRules maps service-relative file paths to their owner.
// Transport-specific generators MUST NOT write to paths owned by another generator.
var ownershipRules = map[string]FileOwner{
	// Shared scaffold owns these files
	"go.mod":                          OwnerShared,
	".gitignore":                      OwnerShared,
	"internal/config/base.go":         OwnerShared,
	"internal/svc/base.go":            OwnerShared,

	// API generator owns these files
	"cmd/api/main.go":                 OwnerAPI,
	"internal/config/api.go":         OwnerAPI,
	"internal/svc/api.go":            OwnerAPI,
	"etc/api.yaml":                   OwnerAPI,

	// RPC generator owns these files
	"cmd/rpc/main.go":                 OwnerRPC,
	"internal/config/rpc.go":         OwnerRPC,
	"internal/svc/rpc.go":            OwnerRPC,
	"etc/rpc.yaml":                   OwnerRPC,
}

// OwnerOf returns the FileOwner for the given service-relative path.
// Returns OwnerShared if the path is not in the rules (conservative default).
func OwnerOf(path string) FileOwner {
	if owner, ok := ownershipRules[path]; ok {
		return owner
	}
	return OwnerShared
}

// IsOwnedBy returns true if the file at the given path is owned by the specified owner.
func IsOwnedBy(path string, owner FileOwner) bool {
	return OwnerOf(path) == owner
}

// CanWrite returns true if the given generator (by owner identity) is allowed to write path.
func CanWrite(path string, writer FileOwner) bool {
	owner := OwnerOf(path)
	// Shared owner may write shared files; API/RPC owners may also write shared files
	// (e.g., during initial scaffold). But API must not write RPC files and vice versa.
	if owner == OwnerShared {
		return true
	}
	return owner == writer
}
