// Code generated by ssgo. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"net/http"
{{if .HasPathParams}}	"strconv"
{{end}}
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"{{.Module}}/internal/api/logic/{{.Group}}"
	"{{.Module}}/internal/pkg/httputil"
	"{{.Module}}/internal/svc"
	"{{.Module}}/internal/api/types"
)

// {{.HandlerName}} handles {{.Method}} {{.Path}}
// @Summary {{.Summary}}
// @Description {{.Doc}}
// @Tags {{.Tag}}
// @Accept json
// @Produce json
{{if .HasPathParams}}// @Param {{.PathParamName}} path {{.PathParamType}} true "{{.PathParamDoc}}"
{{end}}{{if and .HasRequest (not .HasPathParams)}}// @Param request body types.{{.RequestType}} true "Request body"
{{end}}{{if .HasResponse}}// @Success 200 {object} types.Response{data=types.{{.ResponseType}}}
{{end}}// @Failure 400 {object} types.Response
// @Failure 500 {object} types.Response
// @Router {{.FullPath}} [{{.Method | lower}}]
func {{.HandlerName}}(svcCtx *svc.ServiceContext) app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
{{if .HasRequest}}		var req types.{{.RequestType}}

{{if .HasPathParams}}		// Extract {{.PathParamName}} from path parameter
		{{.PathParamName}}Str := c.Param("{{.PathParamName}}")
		if {{.PathParamName}}Str == "" {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Missing {{.PathParamName}} in path",
			})
			return
		}
{{if eq .PathParamGoType "int64"}}
		{{.PathParamName}}, err := strconv.ParseInt({{.PathParamName}}Str, 10, 64)
		if err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Invalid {{.PathParamName}}: must be a number",
			})
			return
		}
		req.{{.PathParamFieldName}} = {{.PathParamName}}
{{else if eq .PathParamGoType "int"}}
		{{.PathParamName}}, err := strconv.Atoi({{.PathParamName}}Str)
		if err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Invalid {{.PathParamName}}: must be a number",
			})
			return
		}
		req.{{.PathParamFieldName}} = {{.PathParamName}}
{{else}}
		req.{{.PathParamFieldName}} = {{.PathParamName}}Str
{{end}}
{{else if eq .Method "GET"}}		// Bind query parameters
		if err := c.BindQuery(&req); err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Invalid query parameters: " + err.Error(),
			})
			return
		}
{{else if eq .Method "DELETE"}}		// Bind path and query parameters
		if err := c.BindQuery(&req); err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Invalid parameters: " + err.Error(),
			})
			return
		}
{{else}}		// Bind JSON body
		if err := c.BindJSON(&req); err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Invalid request body: " + err.Error(),
			})
			return
		}
{{end}}
		// Validate request
		if err := req.Validate(); err != nil {
			c.JSON(consts.StatusBadRequest, types.Response{
				Code:    http.StatusBadRequest,
				Message: "Validation failed: " + err.Error(),
			})
			return
		}

		// Execute business logic
		l := {{.LogicPackage}}.New{{.LogicName}}(ctx, svcCtx)
{{if .HasResponse}}		resp, err := l.{{.LogicMethod}}(&req)
		if err != nil {
			httputil.HandleError(ctx, c, err)
			return
		}

		c.JSON(consts.StatusOK, types.Response{
			Code:    0,
			Message: "success",
			Data:    resp,
		})
{{else}}		err := l.{{.LogicMethod}}(&req)
		if err != nil {
			httputil.HandleError(ctx, c, err)
			return
		}

		c.JSON(consts.StatusOK, types.Response{
			Code:    0,
			Message: "success",
		})
{{end}}{{else}}		// Execute business logic
		l := {{.LogicPackage}}.New{{.LogicName}}(ctx, svcCtx)
{{if .HasResponse}}		resp, err := l.{{.LogicMethod}}()
		if err != nil {
			httputil.HandleError(ctx, c, err)
			return
		}

		c.JSON(consts.StatusOK, types.Response{
			Code:    0,
			Message: "success",
			Data:    resp,
		})
{{else}}		err := l.{{.LogicMethod}}()
		if err != nil {
			httputil.HandleError(ctx, c, err)
			return
		}

		c.JSON(consts.StatusOK, types.Response{
			Code:    0,
			Message: "success",
		})
{{end}}{{end}}	}
}
