// Code generated by ssgo. DO NOT EDIT.

package handler

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"{{.Module}}/internal/api/middleware"
	"{{.Module}}/internal/svc"
{{range .Imports}}	"{{.}}"
{{end}})

// registerGeneratedHandlers registers all API routes generated from .api spec.
// This function is called by RegisterHandlers in routes.go.
func registerGeneratedHandlers(r *server.Hertz, svcCtx *svc.ServiceContext) {
{{range $idx, $group := .Groups}}
	// {{$group.Name}} routes{{if $group.Middleware}} (middleware: {{range $i, $mw := $group.Middleware}}{{if $i}}, {{end}}{{$mw}}{{end}}){{end}}
{{if $group.Prefix}}	{{$group.VarName}}{{$idx}} := r.Group("{{$group.Prefix}}"){{else}}	{{$group.VarName}}{{$idx}} := r.Group(""){{end}}
{{range $group.Middleware}}	{{$group.VarName}}{{$idx}}.Use(middleware.{{.}}(svcCtx))
{{end}}	{
{{range $group.Routes}}		{{$group.VarName}}{{$idx}}.{{.Method}}("{{.Path}}", {{.Package}}.{{.HandlerName}}(svcCtx))
{{end}}	}
{{end}}}
