package bun

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/ssgohq/ssgo/internal/dbparser"
	"github.com/ssgohq/ssgo/tool/internal/generator/naming"
)

// repoData holds data for repository template rendering
type repoData struct {
	PackageName  string
	Imports      []string
	ModelImport  string
	ModelPackage string
	StructName   string
	ModelName    string
	TableName    string
	PrimaryKey   *repoPrimaryKey
	WithTrace    bool
}

type repoPrimaryKey struct {
	Fields    []repoPKField
	Composite bool
}

type repoPKField struct {
	Name   string
	Type   string
	Column string
}

// generateBaseRepository generates the base repository interface
func (g *Generator) generateBaseRepository(dir string) error {
	data := &baseRepoData{
		PackageName: g.opts.RepoPackage,
		WithTrace:   g.opts.WithTrace,
	}

	content, err := g.renderBaseRepoTemplate(data)
	if err != nil {
		return err
	}

	filename := filepath.Join(dir, "base_gen.go")
	g.logVerbose("  Generating base repository: %s\n", filename)

	return os.WriteFile(filename, content, 0o644)
}

type baseRepoData struct {
	PackageName string
	WithTrace   bool
}

// generateRepository generates a single repository file
func (g *Generator) generateRepository(dir string, table *dbparser.Table) error {
	data := g.buildRepoData(table)

	content, err := g.renderRepoTemplate(data)
	if err != nil {
		return err
	}

	filename := filepath.Join(dir, naming.ToSnakeCase(table.Name)+"_repository_gen.go")
	g.logVerbose("  Generating repository: %s\n", filename)

	return os.WriteFile(filename, content, 0o644)
}

// buildRepoData converts table schema to repository template data
func (g *Generator) buildRepoData(table *dbparser.Table) *repoData {
	imports := map[string]bool{
		"context": true,
	}

	// Build primary key info
	var pk *repoPrimaryKey
	hasNonCompositePK := false
	if table.PrimaryKey != nil {
		var fields []repoPKField
		for _, colName := range table.PrimaryKey.Columns {
			col := table.GetColumn(colName)
			if col != nil {
				// Add import for PK type
				if strings.Contains(col.GoType, "uuid.") {
					imports["github.com/google/uuid"] = true
				}

				fields = append(fields, repoPKField{
					Name:   naming.ToPascalCase(colName),
					Type:   col.GoType,
					Column: colName,
				})
			}
		}
		pk = &repoPrimaryKey{
			Fields:    fields,
			Composite: len(fields) > 1,
		}
		hasNonCompositePK = len(fields) == 1
	}

	// Only add tracing imports if we have methods that use them
	if g.opts.WithTrace && hasNonCompositePK {
		imports["fmt"] = true
		imports["go.opentelemetry.io/otel"] = true
		imports["go.opentelemetry.io/otel/attribute"] = true
	} else if g.opts.WithTrace {
		// Composite PK or no PK - only need otel for FindAll/Count
		imports["go.opentelemetry.io/otel"] = true
	}

	// Sort imports
	var importList []string
	for imp := range imports {
		importList = append(importList, imp)
	}
	sort.Strings(importList)

	modelName := naming.ToPascalCase(naming.Singularize(table.Name))

	// Calculate model import path - require module name for proper Go modules
	modelImport := g.opts.ModuleName
	if modelImport != "" {
		modelImport = modelImport + "/" + g.opts.ModelPackage
	} else {
		// Fallback: use package path relative to output dir
		// This requires the user to be in a Go module
		modelImport = g.opts.ModelPackage
	}

	return &repoData{
		PackageName:  g.opts.RepoPackage,
		Imports:      importList,
		ModelImport:  modelImport,
		ModelPackage: g.opts.ModelPackage,
		StructName:   modelName + "Repository",
		ModelName:    modelName,
		TableName:    table.Name,
		PrimaryKey:   pk,
		WithTrace:    g.opts.WithTrace,
	}
}

func (g *Generator) renderBaseRepoTemplate(data *baseRepoData) ([]byte, error) {
	tmpl, err := template.New("base_repo").Parse(baseRepoTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), nil
	}

	return formatted, nil
}

func (g *Generator) renderRepoTemplate(data *repoData) ([]byte, error) {
	funcMap := template.FuncMap{
		"toLower": strings.ToLower,
	}

	tmpl, err := template.New("repo").Funcs(funcMap).Parse(repoTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), nil
	}

	return formatted, nil
}

const baseRepoTemplate = `// Code generated by ss-plugin-db. DO NOT EDIT.
// Source: ss db bun gen

package {{.PackageName}}

import (
	"context"

	"github.com/uptrace/bun"
)

// DB is the database interface used by repositories
type DB interface {
	bun.IDB
}

// BaseRepository provides common repository functionality
type BaseRepository[T any] struct {
	db DB
}

// NewBaseRepository creates a new base repository
func NewBaseRepository[T any](db DB) *BaseRepository[T] {
	return &BaseRepository[T]{db: db}
}

// DB returns the underlying database connection
func (r *BaseRepository[T]) DB() DB {
	return r.db
}

// Query returns a new select query builder
func (r *BaseRepository[T]) Query() *bun.SelectQuery {
	return r.db.NewSelect()
}

// Insert inserts a single record
func (r *BaseRepository[T]) Insert(ctx context.Context, model *T) error {
	_, err := r.db.NewInsert().Model(model).Exec(ctx)
	return err
}

// BulkInsert inserts multiple records
func (r *BaseRepository[T]) BulkInsert(ctx context.Context, models []*T) error {
	if len(models) == 0 {
		return nil
	}
	_, err := r.db.NewInsert().Model(&models).Exec(ctx)
	return err
}

// Update updates a single record
func (r *BaseRepository[T]) Update(ctx context.Context, model *T) error {
	_, err := r.db.NewUpdate().Model(model).WherePK().Exec(ctx)
	return err
}

// Delete deletes a single record
func (r *BaseRepository[T]) Delete(ctx context.Context, model *T) error {
	_, err := r.db.NewDelete().Model(model).WherePK().Exec(ctx)
	return err
}
`

const repoTemplate = `// Code generated by ss-plugin-db. DO NOT EDIT.
// Source: ss db bun gen

package {{.PackageName}}

import (
{{range .Imports}}	"{{.}}"
{{end}}
	"{{.ModelImport}}"
)

// {{.StructName}} provides database operations for {{.ModelName}}
type {{.StructName}} struct {
	*BaseRepository[{{.ModelPackage}}.{{.ModelName}}]
}

// New{{.StructName}} creates a new {{.StructName}}
func New{{.StructName}}(db DB) *{{.StructName}} {
	return &{{.StructName}}{
		BaseRepository: NewBaseRepository[{{.ModelPackage}}.{{.ModelName}}](db),
	}
}

{{if .PrimaryKey}}
{{if not .PrimaryKey.Composite}}
// FindByID finds a {{.ModelName}} by its primary key
func (r *{{.StructName}}) FindByID(ctx context.Context, {{range $i, $f := .PrimaryKey.Fields}}{{if $i}}, {{end}}{{$f.Name | toLower}} {{$f.Type}}{{end}}) (*{{.ModelPackage}}.{{.ModelName}}, error) {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.FindByID")
	defer span.End()
	{{range .PrimaryKey.Fields}}span.SetAttributes(attribute.String("{{.Column}}", fmt.Sprint({{.Name | toLower}})))
	{{end}}
	{{end}}var m {{$.ModelPackage}}.{{.ModelName}}
	err := r.db.NewSelect().
		Model(&m).
		Where("{{(index .PrimaryKey.Fields 0).Column}} = ?", {{(index .PrimaryKey.Fields 0).Name | toLower}}).
		Scan(ctx)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// ExistsByID checks if a {{.ModelName}} exists by its primary key
func (r *{{.StructName}}) ExistsByID(ctx context.Context, {{range $i, $f := .PrimaryKey.Fields}}{{if $i}}, {{end}}{{$f.Name | toLower}} {{$f.Type}}{{end}}) (bool, error) {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.ExistsByID")
	defer span.End()
	{{end}}return r.db.NewSelect().
		Model((*{{$.ModelPackage}}.{{.ModelName}})(nil)).
		Where("{{(index .PrimaryKey.Fields 0).Column}} = ?", {{(index .PrimaryKey.Fields 0).Name | toLower}}).
		Exists(ctx)
}

// DeleteByID deletes a {{.ModelName}} by its primary key
func (r *{{.StructName}}) DeleteByID(ctx context.Context, {{range $i, $f := .PrimaryKey.Fields}}{{if $i}}, {{end}}{{$f.Name | toLower}} {{$f.Type}}{{end}}) error {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.DeleteByID")
	defer span.End()
	{{end}}_, err := r.db.NewDelete().
		Model((*{{$.ModelPackage}}.{{.ModelName}})(nil)).
		Where("{{(index .PrimaryKey.Fields 0).Column}} = ?", {{(index .PrimaryKey.Fields 0).Name | toLower}}).
		Exec(ctx)
	return err
}
{{else}}
// FindByPK finds a {{.ModelName}} by its composite primary key
func (r *{{.StructName}}) FindByPK(ctx context.Context, {{range $i, $f := .PrimaryKey.Fields}}{{if $i}}, {{end}}{{$f.Name | toLower}} {{$f.Type}}{{end}}) (*{{.ModelPackage}}.{{.ModelName}}, error) {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.FindByPK")
	defer span.End()
	{{end}}var m {{$.ModelPackage}}.{{.ModelName}}
	err := r.db.NewSelect().
		Model(&m).
		{{range $i, $f := .PrimaryKey.Fields}}Where("{{$f.Column}} = ?", {{$f.Name | toLower}}).
		{{end}}Scan(ctx)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
{{end}}
{{end}}

// FindAll returns all {{.ModelName}} records
func (r *{{.StructName}}) FindAll(ctx context.Context) ([]*{{.ModelPackage}}.{{.ModelName}}, error) {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.FindAll")
	defer span.End()
	{{end}}var models []*{{$.ModelPackage}}.{{.ModelName}}
	err := r.db.NewSelect().Model(&models).Scan(ctx)
	return models, err
}

// Count returns the total count of {{.ModelName}} records
func (r *{{.StructName}}) Count(ctx context.Context) (int, error) {
	{{if $.WithTrace}}ctx, span := otel.Tracer("").Start(ctx, "{{.StructName}}.Count")
	defer span.End()
	{{end}}return r.db.NewSelect().Model((*{{$.ModelPackage}}.{{.ModelName}})(nil)).Count(ctx)
}
`
