// Code generated by ssgo. DO NOT EDIT.

package types

import (
	"errors"
	"fmt"
)

// Response is the standard API response wrapper
type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

// PagedResponse is the response wrapper for paginated results
type PagedResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Total   int64       `json:"total"`
	Page    int         `json:"page"`
	Size    int         `json:"size"`
}

// Validatable interface for request validation
type Validatable interface {
	Validate() error
}

// DefaultApplicable interface for applying default values
type DefaultApplicable interface {
	ApplyDefaults()
}

// ValidationError represents a validation error
type ValidationError struct {
	Field   string
	Message string
}

func (e ValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Field, e.Message)
}

// ValidationErrors represents multiple validation errors
type ValidationErrors []ValidationError

func (e ValidationErrors) Error() string {
	if len(e) == 0 {
		return ""
	}
	if len(e) == 1 {
		return e[0].Error()
	}
	return fmt.Sprintf("%s (and %d more errors)", e[0].Error(), len(e)-1)
}

{{range .Types}}
{{if .IsAlias}}
// {{.Name}} is a type alias for {{.AliasOf}}
type {{.Name}} = {{.AliasOf}}
{{else}}
{{if .Comment}}// {{.Name}} {{.Comment}}{{else}}// {{.Name}} represents {{.Name | ToSnakeCase}} data{{end}}
type {{.Name}} struct {
{{range .Fields}}	{{.Name}} {{.Type}} `json:"{{.JSONTag}}"{{if .Validate}} validate:"{{.Validate}}"{{end}}`{{if .Comment}} // {{.Comment}}{{end}}
{{end}}}

// Validate validates the {{.Name}} fields
func (r *{{.Name}}) Validate() error {
	var errs ValidationErrors
{{range .Fields}}
{{- if .Required}}
	if r.{{.Name}} == {{.ZeroValue}} {
		errs = append(errs, ValidationError{Field: "{{.JSONTag}}", Message: "is required"})
	}
{{- end}}
{{- if .RangeMin}}
	if r.{{.Name}} < {{.RangeMin}} {
		errs = append(errs, ValidationError{Field: "{{.JSONTag}}", Message: fmt.Sprintf("must be >= %v", {{.RangeMin}})})
	}
{{- end}}
{{- if .RangeMax}}
	if r.{{.Name}} > {{.RangeMax}} {
		errs = append(errs, ValidationError{Field: "{{.JSONTag}}", Message: fmt.Sprintf("must be <= %v", {{.RangeMax}})})
	}
{{- end}}
{{- if .Options}}
	if !isValidOption(r.{{.Name}}, []{{.Type}}{{"{"}}{{range $i, $opt := .Options}}{{if $i}}, {{end}}"{{$opt}}"{{end}}{{"}"}}) {
		errs = append(errs, ValidationError{Field: "{{.JSONTag}}", Message: fmt.Sprintf("must be one of: {{range $i, $opt := .Options}}{{if $i}}, {{end}}{{$opt}}{{end}}")})
	}
{{- end}}
{{end}}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// ApplyDefaults applies default values to {{.Name}} fields
func (r *{{.Name}}) ApplyDefaults() {
{{range .Fields}}
{{- if .Default}}
	if r.{{.Name}} == {{.ZeroValue}} {
		r.{{.Name}} = {{.DefaultValue}}
	}
{{- end}}
{{end}}
}
{{end}}
{{end}}

// isValidOption checks if value is in the allowed options list
func isValidOption[T comparable](value T, options []T) bool {
	for _, opt := range options {
		if value == opt {
			return true
		}
	}
	return false
}

// Ensure errors package is used (to avoid unused import warning)
var _ = errors.New