// Code generated by ssgo. DO NOT EDIT.
// Run 'ssgo gen' to regenerate.

package main

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/ssgohq/goten-core/app"
{{- if .WithAPI}}
	"github.com/ssgohq/goten-core/lifecycle"
	"github.com/ssgohq/goten-core/logx"
	"{{.Module}}/internal/api/handler"
{{- end}}
	"gopkg.in/yaml.v3"

	"{{.Module}}/internal/config"
	"{{.Module}}/internal/svc"
)
{{- if .WithAPI}}

var apiConfigFile = flag.String("api-c", "etc/api.yaml", "API config file")
{{- end}}
{{- if .WithRPC}}

var rpcConfigFile = flag.String("rpc-c", "etc/rpc.yaml", "RPC config file")
{{- end}}

func main() {
	flag.Parse()

	application := app.New(app.Config{Name: "{{.ServiceName}}"})
{{- if .WithAPI}}

	apiCfg := mustLoadAPIConfig(*apiConfigFile)
	logx.Init(apiCfg.Log)
	apiSvcCtx := svc.NewAPIServiceContext(apiCfg)

	addr := fmt.Sprintf("%s:%d", apiCfg.Host, apiCfg.Port)
	h := app.NewHertzServer(addr, app.WithTracing(apiCfg.IsTraceEnabled()))
	handler.RegisterHandlers(h, apiSvcCtx)
	application.AddService(lifecycle.NewHertzAdapter("api", h))
{{- end}}
{{- if .WithRPC}}

	rpcCfg := mustLoadRPCConfig(*rpcConfigFile)
	rpcSvcCtx, err := svc.NewRPCServiceContext(rpcCfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to init RPC service context: %v\n", err)
		os.Exit(1)
	}
	_ = rpcSvcCtx // wire your Kitex server here (see cmd/rpc/main.go for reference)
{{- end}}

	application.MustRun(context.Background())
}
{{- if .WithAPI}}

func mustLoadAPIConfig(path string) config.APIConfig {
	var c config.APIConfig
	data, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Sprintf("failed to read API config: %v", err))
	}
	if err := yaml.Unmarshal(data, &c); err != nil {
		panic(fmt.Sprintf("failed to parse API config: %v", err))
	}
	return c
}
{{- end}}
{{- if .WithRPC}}

func mustLoadRPCConfig(path string) config.RPCConfig {
	var c config.RPCConfig
	data, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Sprintf("failed to read RPC config: %v", err))
	}
	if err := yaml.Unmarshal(data, &c); err != nil {
		panic(fmt.Sprintf("failed to parse RPC config: %v", err))
	}
	c.ServerConfig.SetDefaults()
	return c
}
{{- end}}
