// Code generated by ssgo. DO NOT EDIT.

package server

import (
	"context"

	"{{.Module}}/internal/rpc/logic"
	"{{.Module}}/internal/svc"
	{{.ServiceLower}} "{{.TypesImport}}"
)

// {{.Service}}Server implements the {{.Service}} service interface.
// Each method delegates to its corresponding logic.
type {{.Service}}Server struct {
	svcCtx *svc.ServiceContext
}

// New{{.Service}}Server creates a new {{.Service}}Server
func New{{.Service}}Server(svcCtx *svc.ServiceContext) *{{.Service}}Server {
	return &{{.Service}}Server{svcCtx: svcCtx}
}

{{range .Methods}}
// {{.Name}} handles the {{.Name}} RPC request
func (s *{{$.Service}}Server) {{.Name}}(ctx context.Context, req *{{$.ServiceLower}}.{{.RequestType}}) (*{{$.ServiceLower}}.{{.ResponseType}}, error) {
	l := logic.New{{.Name}}Logic(ctx, s.svcCtx)
	return l.{{.Name}}(req)
}
{{end}}