// Package sqlc provides code generation for SQLC-based database layers
package sqlc

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/ssgohq/ssgo/tool/internal/generator/common"
)

// ModelInfo represents information about a SQLC model
type ModelInfo struct {
	Name   string
	Fields []FieldInfo
}

// FieldInfo represents a field in a model
type FieldInfo struct {
	Name     string
	Type     string
	JSONTag  string
	DBColumn string
}

// Parser parses SQLC generated code
type Parser struct {
	dbDir   string
	verbose bool
}

// NewParser creates a new Parser
func NewParser(dbDir string, verbose bool) *Parser {
	return &Parser{
		dbDir:   dbDir,
		verbose: verbose,
	}
}

// ParseModels parses the models.go file generated by SQLC
func (p *Parser) ParseModels() ([]ModelInfo, error) {
	modelsPath := filepath.Join(p.dbDir, "models.go")
	if _, err := os.Stat(modelsPath); os.IsNotExist(err) {
		return nil, fmt.Errorf("models.go not found. Run 'sqlc generate' first")
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, modelsPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("failed to parse models.go: %w", err)
	}

	var models []ModelInfo
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			model := ModelInfo{
				Name: typeSpec.Name.Name,
			}

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}

				fieldInfo := FieldInfo{
					Name: field.Names[0].Name,
					Type: p.typeToString(field.Type),
				}

				// Parse struct tags
				if field.Tag != nil {
					tag := field.Tag.Value
					fieldInfo.JSONTag = p.extractTag(tag, "json")
					fieldInfo.DBColumn = p.extractTag(tag, "db")
				}

				model.Fields = append(model.Fields, fieldInfo)
			}

			models = append(models, model)
		}
	}

	return models, nil
}

// ParseQueries parses the querier.go interface generated by SQLC
func (p *Parser) ParseQueries() ([]common.QueryInfo, error) {
	querierPath := filepath.Join(p.dbDir, "querier.go")
	if _, err := os.Stat(querierPath); os.IsNotExist(err) {
		return nil, fmt.Errorf("querier.go not found. Run 'sqlc generate' first")
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, querierPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("failed to parse querier.go: %w", err)
	}

	return p.extractQueriesFromAST(node), nil
}

// extractQueriesFromAST extracts QueryInfo from parsed AST
func (p *Parser) extractQueriesFromAST(node *ast.File) []common.QueryInfo {
	var queries []common.QueryInfo

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		queries = append(queries, p.extractQueriesFromGenDecl(genDecl)...)
	}

	return queries
}

// extractQueriesFromGenDecl extracts queries from a type declaration
func (p *Parser) extractQueriesFromGenDecl(genDecl *ast.GenDecl) []common.QueryInfo {
	var queries []common.QueryInfo

	for _, spec := range genDecl.Specs {
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok || typeSpec.Name.Name != "Querier" {
			continue
		}

		ifaceType, ok := typeSpec.Type.(*ast.InterfaceType)
		if !ok {
			continue
		}

		queries = append(queries, p.extractQueriesFromInterface(ifaceType)...)
	}

	return queries
}

// extractQueriesFromInterface extracts queries from an interface type
func (p *Parser) extractQueriesFromInterface(ifaceType *ast.InterfaceType) []common.QueryInfo {
	var queries []common.QueryInfo

	for _, method := range ifaceType.Methods.List {
		if len(method.Names) == 0 {
			continue
		}

		funcType, ok := method.Type.(*ast.FuncType)
		if !ok {
			continue
		}

		query := p.parseMethodAsQuery(method.Names[0].Name, funcType)
		queries = append(queries, query)
	}

	return queries
}

// parseMethodAsQuery parses a method as QueryInfo
func (p *Parser) parseMethodAsQuery(name string, funcType *ast.FuncType) common.QueryInfo {
	query := common.QueryInfo{Name: name}

	p.parseQueryReturnType(&query, funcType)
	p.parseQueryParams(&query, funcType)

	return query
}

// parseQueryReturnType parses and sets the return type for a query
func (p *Parser) parseQueryReturnType(query *common.QueryInfo, funcType *ast.FuncType) {
	if funcType.Results == nil || len(funcType.Results.List) == 0 {
		return
	}

	// First result is the actual return type (second is error)
	result := funcType.Results.List[0]
	query.ReturnType = p.typeToString(result.Type)

	// Check if it's just error (exec query)
	if query.ReturnType == "error" {
		query.IsExec = true
		query.ReturnType = ""
		return
	}

	query.IsMany = strings.HasPrefix(query.ReturnType, "[]")
	query.ModelName = p.extractModelName(query.ReturnType)
}

// parseQueryParams parses and sets the parameters for a query
func (p *Parser) parseQueryParams(query *common.QueryInfo, funcType *ast.FuncType) {
	if funcType.Params == nil {
		return
	}

	for i, param := range funcType.Params.List {
		// Skip context.Context (first param)
		if i == 0 {
			continue
		}

		paramType := p.typeToString(param.Type)
		if len(param.Names) > 0 {
			for _, name := range param.Names {
				query.Params = append(query.Params, common.Param{
					Name: name.Name,
					Type: paramType,
				})
			}
		} else {
			// Anonymous parameter
			query.Params = append(query.Params, common.Param{
				Name: fmt.Sprintf("arg%d", i),
				Type: paramType,
			})
		}
	}
}

// typeToString converts an ast.Expr type to string
func (p *Parser) typeToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + p.typeToString(t.X)
	case *ast.ArrayType:
		return "[]" + p.typeToString(t.Elt)
	case *ast.SelectorExpr:
		return p.typeToString(t.X) + "." + t.Sel.Name
	case *ast.MapType:
		return "map[" + p.typeToString(t.Key) + "]" + p.typeToString(t.Value)
	default:
		return "interface{}"
	}
}

// extractTag extracts a tag value from a struct tag string
func (p *Parser) extractTag(tagStr, tagName string) string {
	// Remove backticks
	tagStr = strings.Trim(tagStr, "`")

	// Find the tag
	parts := strings.Split(tagStr, " ")
	for _, part := range parts {
		if strings.HasPrefix(part, tagName+":") {
			value := strings.TrimPrefix(part, tagName+":")
			value = strings.Trim(value, "\"")
			// Get first part before comma
			if idx := strings.Index(value, ","); idx != -1 {
				value = value[:idx]
			}
			return value
		}
	}
	return ""
}

// extractModelName extracts the model name from a return type
func (p *Parser) extractModelName(returnType string) string {
	// Remove pointer and slice prefixes
	name := strings.TrimPrefix(returnType, "*")
	name = strings.TrimPrefix(name, "[]")
	name = strings.TrimPrefix(name, "*")

	// Remove package prefix if any
	if idx := strings.LastIndex(name, "."); idx != -1 {
		name = name[idx+1:]
	}

	return name
}

// GetModelByName returns a model by name
func (p *Parser) GetModelByName(models []ModelInfo, name string) *ModelInfo {
	for _, m := range models {
		if m.Name == name {
			return &m
		}
	}
	return nil
}
