-- {{.Entity.Name}} queries
-- Generated by ss db sqlc init
-- Edit this file to add your custom queries

-- SQLC Query Annotations:
-- :one     - Returns a single row
-- :many    - Returns multiple rows  
-- :exec    - Executes without returning rows
-- :execrows - Executes and returns affected row count
-- :execresult - Executes and returns sql.Result

{{if .SchemaName}}-- Schema: {{.SchemaName}}
{{end}}
{{if .IsPostgres}}
-- name: Get{{.Entity.Name}}ByID :one
SELECT * FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
WHERE id = $1 LIMIT 1;

-- name: List{{.Entity.PluralName}} :many
SELECT * FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
ORDER BY id DESC
LIMIT $1 OFFSET $2;

-- name: Count{{.Entity.PluralName}} :one
SELECT COUNT(*) FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}};

-- name: Create{{.Entity.Name}} :one
INSERT INTO {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}} (
    -- TODO: Add your columns here
    created_at, updated_at
) VALUES (
    NOW(), NOW()
)
RETURNING *;

-- name: Update{{.Entity.Name}} :one
UPDATE {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
SET updated_at = NOW()
    -- TODO: Add your SET clauses here
WHERE id = $1
RETURNING *;

-- name: Delete{{.Entity.Name}} :exec
DELETE FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
WHERE id = $1;
{{else}}
-- name: Get{{.Entity.Name}}ByID :one
SELECT * FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
WHERE id = ? LIMIT 1;

-- name: List{{.Entity.PluralName}} :many
SELECT * FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
ORDER BY id DESC
LIMIT ? OFFSET ?;

-- name: Count{{.Entity.PluralName}} :one
SELECT COUNT(*) FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}};

-- name: Create{{.Entity.Name}} :execresult
INSERT INTO {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}} (
    -- TODO: Add your columns here
    created_at, updated_at
) VALUES (
    NOW(), NOW()
);

-- name: Update{{.Entity.Name}} :exec
UPDATE {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
SET updated_at = NOW()
    -- TODO: Add your SET clauses here
WHERE id = ?;

-- name: Delete{{.Entity.Name}} :exec
DELETE FROM {{if .SchemaName}}{{.SchemaName}}.{{end}}{{.TableName}}
WHERE id = ?;
{{end}}